// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain-protos.proto

package care.solve.blockchain.entity.proto;

public final class BlockchainProtos {
  private BlockchainProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code main.Functions}
   */
  public enum Functions
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GET_EVENT = 0;</code>
     */
    GET_EVENT(0),
    /**
     * <code>SAVE_EVENT = 1;</code>
     */
    SAVE_EVENT(1),
    /**
     * <code>GET_USER_PROFILE = 2;</code>
     */
    GET_USER_PROFILE(2),
    /**
     * <code>SAVE_USER_PROFILE = 3;</code>
     */
    SAVE_USER_PROFILE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GET_EVENT = 0;</code>
     */
    public static final int GET_EVENT_VALUE = 0;
    /**
     * <code>SAVE_EVENT = 1;</code>
     */
    public static final int SAVE_EVENT_VALUE = 1;
    /**
     * <code>GET_USER_PROFILE = 2;</code>
     */
    public static final int GET_USER_PROFILE_VALUE = 2;
    /**
     * <code>SAVE_USER_PROFILE = 3;</code>
     */
    public static final int SAVE_USER_PROFILE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Functions valueOf(int value) {
      return forNumber(value);
    }

    public static Functions forNumber(int value) {
      switch (value) {
        case 0: return GET_EVENT;
        case 1: return SAVE_EVENT;
        case 2: return GET_USER_PROFILE;
        case 3: return SAVE_USER_PROFILE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Functions>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Functions> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Functions>() {
            public Functions findValueByNumber(int number) {
              return Functions.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return care.solve.blockchain.entity.proto.BlockchainProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final Functions[] VALUES = values();

    public static Functions valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Functions(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:main.Functions)
  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:main.Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>uint64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string source = 4;</code>
     */
    java.lang.String getSource();
    /**
     * <code>string source = 4;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>string data = 5;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 5;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code main.Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:main.Event)
      EventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
      id_ = "";
      timestamp_ = 0L;
      type_ = "";
      source_ = "";
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              source_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              care.solve.blockchain.entity.proto.BlockchainProtos.Event.class, care.solve.blockchain.entity.proto.BlockchainProtos.Event.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 4;
    private volatile java.lang.Object source_;
    /**
     * <code>string source = 4;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      }
    }
    /**
     * <code>string source = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 5;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(2, timestamp_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (!getSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, source_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (!getSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, source_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof care.solve.blockchain.entity.proto.BlockchainProtos.Event)) {
        return super.equals(obj);
      }
      care.solve.blockchain.entity.proto.BlockchainProtos.Event other = (care.solve.blockchain.entity.proto.BlockchainProtos.Event) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getType()
          .equals(other.getType());
      result = result && getSource()
          .equals(other.getSource());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(care.solve.blockchain.entity.proto.BlockchainProtos.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code main.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:main.Event)
        care.solve.blockchain.entity.proto.BlockchainProtos.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                care.solve.blockchain.entity.proto.BlockchainProtos.Event.class, care.solve.blockchain.entity.proto.BlockchainProtos.Event.Builder.class);
      }

      // Construct using care.solve.blockchain.entity.proto.BlockchainProtos.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        timestamp_ = 0L;

        type_ = "";

        source_ = "";

        data_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_Event_descriptor;
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.Event getDefaultInstanceForType() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.Event.getDefaultInstance();
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.Event build() {
        care.solve.blockchain.entity.proto.BlockchainProtos.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.Event buildPartial() {
        care.solve.blockchain.entity.proto.BlockchainProtos.Event result = new care.solve.blockchain.entity.proto.BlockchainProtos.Event(this);
        result.id_ = id_;
        result.timestamp_ = timestamp_;
        result.type_ = type_;
        result.source_ = source_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof care.solve.blockchain.entity.proto.BlockchainProtos.Event) {
          return mergeFrom((care.solve.blockchain.entity.proto.BlockchainProtos.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(care.solve.blockchain.entity.proto.BlockchainProtos.Event other) {
        if (other == care.solve.blockchain.entity.proto.BlockchainProtos.Event.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getSource().isEmpty()) {
          source_ = other.source_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        care.solve.blockchain.entity.proto.BlockchainProtos.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (care.solve.blockchain.entity.proto.BlockchainProtos.Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>string source = 4;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string source = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string source = 4;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string source = 4;</code>
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>string source = 4;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        source_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 5;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:main.Event)
    }

    // @@protoc_insertion_point(class_scope:main.Event)
    private static final care.solve.blockchain.entity.proto.BlockchainProtos.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new care.solve.blockchain.entity.proto.BlockchainProtos.Event();
    }

    public static care.solve.blockchain.entity.proto.BlockchainProtos.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    public care.solve.blockchain.entity.proto.BlockchainProtos.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:main.UserProfile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>.main.EncryptedData encryptedData = 2;</code>
     */
    boolean hasEncryptedData();
    /**
     * <code>.main.EncryptedData encryptedData = 2;</code>
     */
    care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData getEncryptedData();
    /**
     * <code>.main.EncryptedData encryptedData = 2;</code>
     */
    care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedDataOrBuilder getEncryptedDataOrBuilder();
  }
  /**
   * Protobuf type {@code main.UserProfile}
   */
  public  static final class UserProfile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:main.UserProfile)
      UserProfileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserProfile.newBuilder() to construct.
    private UserProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserProfile() {
      userId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserProfile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.Builder subBuilder = null;
              if (encryptedData_ != null) {
                subBuilder = encryptedData_.toBuilder();
              }
              encryptedData_ = input.readMessage(care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(encryptedData_);
                encryptedData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_UserProfile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_UserProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile.class, care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTEDDATA_FIELD_NUMBER = 2;
    private care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData encryptedData_;
    /**
     * <code>.main.EncryptedData encryptedData = 2;</code>
     */
    public boolean hasEncryptedData() {
      return encryptedData_ != null;
    }
    /**
     * <code>.main.EncryptedData encryptedData = 2;</code>
     */
    public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData getEncryptedData() {
      return encryptedData_ == null ? care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.getDefaultInstance() : encryptedData_;
    }
    /**
     * <code>.main.EncryptedData encryptedData = 2;</code>
     */
    public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedDataOrBuilder getEncryptedDataOrBuilder() {
      return getEncryptedData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (encryptedData_ != null) {
        output.writeMessage(2, getEncryptedData());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (encryptedData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEncryptedData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile)) {
        return super.equals(obj);
      }
      care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile other = (care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && (hasEncryptedData() == other.hasEncryptedData());
      if (hasEncryptedData()) {
        result = result && getEncryptedData()
            .equals(other.getEncryptedData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      if (hasEncryptedData()) {
        hash = (37 * hash) + ENCRYPTEDDATA_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code main.UserProfile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:main.UserProfile)
        care.solve.blockchain.entity.proto.BlockchainProtos.UserProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_UserProfile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_UserProfile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile.class, care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile.Builder.class);
      }

      // Construct using care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        if (encryptedDataBuilder_ == null) {
          encryptedData_ = null;
        } else {
          encryptedData_ = null;
          encryptedDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_UserProfile_descriptor;
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile getDefaultInstanceForType() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile.getDefaultInstance();
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile build() {
        care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile buildPartial() {
        care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile result = new care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile(this);
        result.userId_ = userId_;
        if (encryptedDataBuilder_ == null) {
          result.encryptedData_ = encryptedData_;
        } else {
          result.encryptedData_ = encryptedDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile) {
          return mergeFrom((care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile other) {
        if (other == care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasEncryptedData()) {
          mergeEncryptedData(other.getEncryptedData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData encryptedData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData, care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.Builder, care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedDataOrBuilder> encryptedDataBuilder_;
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      public boolean hasEncryptedData() {
        return encryptedDataBuilder_ != null || encryptedData_ != null;
      }
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData getEncryptedData() {
        if (encryptedDataBuilder_ == null) {
          return encryptedData_ == null ? care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.getDefaultInstance() : encryptedData_;
        } else {
          return encryptedDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      public Builder setEncryptedData(care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData value) {
        if (encryptedDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          encryptedData_ = value;
          onChanged();
        } else {
          encryptedDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      public Builder setEncryptedData(
          care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.Builder builderForValue) {
        if (encryptedDataBuilder_ == null) {
          encryptedData_ = builderForValue.build();
          onChanged();
        } else {
          encryptedDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      public Builder mergeEncryptedData(care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData value) {
        if (encryptedDataBuilder_ == null) {
          if (encryptedData_ != null) {
            encryptedData_ =
              care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.newBuilder(encryptedData_).mergeFrom(value).buildPartial();
          } else {
            encryptedData_ = value;
          }
          onChanged();
        } else {
          encryptedDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      public Builder clearEncryptedData() {
        if (encryptedDataBuilder_ == null) {
          encryptedData_ = null;
          onChanged();
        } else {
          encryptedData_ = null;
          encryptedDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.Builder getEncryptedDataBuilder() {
        
        onChanged();
        return getEncryptedDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedDataOrBuilder getEncryptedDataOrBuilder() {
        if (encryptedDataBuilder_ != null) {
          return encryptedDataBuilder_.getMessageOrBuilder();
        } else {
          return encryptedData_ == null ?
              care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.getDefaultInstance() : encryptedData_;
        }
      }
      /**
       * <code>.main.EncryptedData encryptedData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData, care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.Builder, care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedDataOrBuilder> 
          getEncryptedDataFieldBuilder() {
        if (encryptedDataBuilder_ == null) {
          encryptedDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData, care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.Builder, care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedDataOrBuilder>(
                  getEncryptedData(),
                  getParentForChildren(),
                  isClean());
          encryptedData_ = null;
        }
        return encryptedDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:main.UserProfile)
    }

    // @@protoc_insertion_point(class_scope:main.UserProfile)
    private static final care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile();
    }

    public static care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserProfile>
        PARSER = new com.google.protobuf.AbstractParser<UserProfile>() {
      public UserProfile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserProfile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserProfile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserProfile> getParserForType() {
      return PARSER;
    }

    public care.solve.blockchain.entity.proto.BlockchainProtos.UserProfile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EncryptedDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:main.EncryptedData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string encryptedPayload = 1;</code>
     */
    java.lang.String getEncryptedPayload();
    /**
     * <code>string encryptedPayload = 1;</code>
     */
    com.google.protobuf.ByteString
        getEncryptedPayloadBytes();

    /**
     * <code>string cbcInitialVector = 2;</code>
     */
    java.lang.String getCbcInitialVector();
    /**
     * <code>string cbcInitialVector = 2;</code>
     */
    com.google.protobuf.ByteString
        getCbcInitialVectorBytes();
  }
  /**
   * Protobuf type {@code main.EncryptedData}
   */
  public  static final class EncryptedData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:main.EncryptedData)
      EncryptedDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EncryptedData.newBuilder() to construct.
    private EncryptedData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EncryptedData() {
      encryptedPayload_ = "";
      cbcInitialVector_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EncryptedData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              encryptedPayload_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cbcInitialVector_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_EncryptedData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_EncryptedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.class, care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.Builder.class);
    }

    public static final int ENCRYPTEDPAYLOAD_FIELD_NUMBER = 1;
    private volatile java.lang.Object encryptedPayload_;
    /**
     * <code>string encryptedPayload = 1;</code>
     */
    public java.lang.String getEncryptedPayload() {
      java.lang.Object ref = encryptedPayload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encryptedPayload_ = s;
        return s;
      }
    }
    /**
     * <code>string encryptedPayload = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEncryptedPayloadBytes() {
      java.lang.Object ref = encryptedPayload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encryptedPayload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CBCINITIALVECTOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object cbcInitialVector_;
    /**
     * <code>string cbcInitialVector = 2;</code>
     */
    public java.lang.String getCbcInitialVector() {
      java.lang.Object ref = cbcInitialVector_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cbcInitialVector_ = s;
        return s;
      }
    }
    /**
     * <code>string cbcInitialVector = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCbcInitialVectorBytes() {
      java.lang.Object ref = cbcInitialVector_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cbcInitialVector_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEncryptedPayloadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, encryptedPayload_);
      }
      if (!getCbcInitialVectorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cbcInitialVector_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEncryptedPayloadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, encryptedPayload_);
      }
      if (!getCbcInitialVectorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cbcInitialVector_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData)) {
        return super.equals(obj);
      }
      care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData other = (care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData) obj;

      boolean result = true;
      result = result && getEncryptedPayload()
          .equals(other.getEncryptedPayload());
      result = result && getCbcInitialVector()
          .equals(other.getCbcInitialVector());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENCRYPTEDPAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedPayload().hashCode();
      hash = (37 * hash) + CBCINITIALVECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getCbcInitialVector().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code main.EncryptedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:main.EncryptedData)
        care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_EncryptedData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_EncryptedData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.class, care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.Builder.class);
      }

      // Construct using care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        encryptedPayload_ = "";

        cbcInitialVector_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.internal_static_main_EncryptedData_descriptor;
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData getDefaultInstanceForType() {
        return care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.getDefaultInstance();
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData build() {
        care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData buildPartial() {
        care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData result = new care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData(this);
        result.encryptedPayload_ = encryptedPayload_;
        result.cbcInitialVector_ = cbcInitialVector_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData) {
          return mergeFrom((care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData other) {
        if (other == care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData.getDefaultInstance()) return this;
        if (!other.getEncryptedPayload().isEmpty()) {
          encryptedPayload_ = other.encryptedPayload_;
          onChanged();
        }
        if (!other.getCbcInitialVector().isEmpty()) {
          cbcInitialVector_ = other.cbcInitialVector_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object encryptedPayload_ = "";
      /**
       * <code>string encryptedPayload = 1;</code>
       */
      public java.lang.String getEncryptedPayload() {
        java.lang.Object ref = encryptedPayload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          encryptedPayload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string encryptedPayload = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEncryptedPayloadBytes() {
        java.lang.Object ref = encryptedPayload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encryptedPayload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string encryptedPayload = 1;</code>
       */
      public Builder setEncryptedPayload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encryptedPayload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string encryptedPayload = 1;</code>
       */
      public Builder clearEncryptedPayload() {
        
        encryptedPayload_ = getDefaultInstance().getEncryptedPayload();
        onChanged();
        return this;
      }
      /**
       * <code>string encryptedPayload = 1;</code>
       */
      public Builder setEncryptedPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        encryptedPayload_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cbcInitialVector_ = "";
      /**
       * <code>string cbcInitialVector = 2;</code>
       */
      public java.lang.String getCbcInitialVector() {
        java.lang.Object ref = cbcInitialVector_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cbcInitialVector_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cbcInitialVector = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCbcInitialVectorBytes() {
        java.lang.Object ref = cbcInitialVector_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cbcInitialVector_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cbcInitialVector = 2;</code>
       */
      public Builder setCbcInitialVector(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cbcInitialVector_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cbcInitialVector = 2;</code>
       */
      public Builder clearCbcInitialVector() {
        
        cbcInitialVector_ = getDefaultInstance().getCbcInitialVector();
        onChanged();
        return this;
      }
      /**
       * <code>string cbcInitialVector = 2;</code>
       */
      public Builder setCbcInitialVectorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cbcInitialVector_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:main.EncryptedData)
    }

    // @@protoc_insertion_point(class_scope:main.EncryptedData)
    private static final care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData();
    }

    public static care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncryptedData>
        PARSER = new com.google.protobuf.AbstractParser<EncryptedData>() {
      public EncryptedData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EncryptedData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EncryptedData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EncryptedData> getParserForType() {
      return PARSER;
    }

    public care.solve.blockchain.entity.proto.BlockchainProtos.EncryptedData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_main_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_main_Event_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_main_UserProfile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_main_UserProfile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_main_EncryptedData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_main_EncryptedData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027blockchain-protos.proto\022\004main\"R\n\005Event" +
      "\022\n\n\002id\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\004\022\014\n\004type\030" +
      "\003 \001(\t\022\016\n\006source\030\004 \001(\t\022\014\n\004data\030\005 \001(\t\"I\n\013U" +
      "serProfile\022\016\n\006userId\030\001 \001(\t\022*\n\rencryptedD" +
      "ata\030\002 \001(\0132\023.main.EncryptedData\"C\n\rEncryp" +
      "tedData\022\030\n\020encryptedPayload\030\001 \001(\t\022\030\n\020cbc" +
      "InitialVector\030\002 \001(\t*W\n\tFunctions\022\r\n\tGET_" +
      "EVENT\020\000\022\016\n\nSAVE_EVENT\020\001\022\024\n\020GET_USER_PROF" +
      "ILE\020\002\022\025\n\021SAVE_USER_PROFILE\020\003B<\n\"care.sol" +
      "ve.blockchain.entity.protoB\020BlockchainPr" +
      "otosZ\004mainb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_main_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_main_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_main_Event_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "Type", "Source", "Data", });
    internal_static_main_UserProfile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_main_UserProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_main_UserProfile_descriptor,
        new java.lang.String[] { "UserId", "EncryptedData", });
    internal_static_main_EncryptedData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_main_EncryptedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_main_EncryptedData_descriptor,
        new java.lang.String[] { "EncryptedPayload", "CbcInitialVector", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
